name: Compile DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64  # Change to x86 if targeting 32-bit systems

    - name: Compile DLL
      run: |
        cl.exe /LD main.cpp /Fe:RunCommand.dll shell32.lib atl.lib
        dir
      shell: cmd

